import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Navbar from '@/app/components/navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Recipe Search & Save',
  description: 'Generated by create next app',
}

// default layout: includes Navbar
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" href="./chef_hat_2.png" sizes="any" />
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
